CREATE TABLE CustomerInfo(
    CUSTOMER_NO CHAR(5),
    CUSTOMER_GRADE VARCHAR2(10) NOT NULL,
    JOINDATE TIMESTAMP,
    LASTVISIT TIMESTAMP,
    IDENTIFICATION_METHOD VARCHAR2(7),
    SEX CHAR(1),
    AGE VARCHAR2(3),
    ADDR_R VARCHAR2(200),
    ADDR_N VARCHAR2(200)
);

CREATE TABLE OrderInfo(
    ORDER_NO CHAR(16),
    TURN_NO VARCHAR2(3) NOT NULL,
    ORDERDATE TIMESTAMP,
    PROGRESS VARCHAR2(20) NOT NULL,
    SHIPPING_ADDR VARCHAR2(200),
    PRODUCT_NO CHAR(16),
    PRODUCT_NAME VARCHAR2(200),
    OPTION_NAME VARCHAR2(400),
    AMOUNT NUMBER(10) NOT NULL,
    PRICE NUMBER(10),
    SHIPPING_CHARGE NUMBER(7),
    COUPON_PRICE NUMBER(10),
    CUSTOMER_ORDER CHAR(1) NOT NULL,
    CUSTOMER_NO CHAR(5)
);

CREATE TABLE PayInfo(
    PAY_NO VARCHAR2(6),
    ORDER_NO CHAR(16),
    PAYDATE TIMESTAMP,
    PAY_PROGRESS CHAR(20) NOT NULL,
    PAY_METHOD VARCHAR2(30) NOT NULL,
    PAY_AMOUNT NUMBER(10),
    CARD_COMPANY VARCHAR2(50),
    LOAN_MONTH NUMBER(2)
);

CREATE TABLE ProductInfo(
    PRODUCT_NO CHAR(16),
    PRODUCT_NAME VARCHAR2(400),
    COMPANY_NAME VARCHAR2(400),
    CATEGORY_NAME VARCHAR2(400),
    BRAND_NAME VARCHAR2(400),
    PRODUCT_CLASS VARCHAR2(30),
    R_PRICE NUMBER(10), --대표 판매가
    SHIPPING_CHARGE VARCHAR2(50),
    SALE_STATUS CHAR(20),
    DISPLAY_STATUS CHAR(2)
);

CREATE TABLE RefundInfo(
    REFUND_NO VARCHAR2(6),
    ORDER_NO CHAR(16),
    REFUND_PROGRESS CHAR(50) NOT NULL,
    PAY_METHOD VARCHAR2(50) NOT NULL,
    REFUND_PRICE NUMBER(10),
    LOAN_MONTH NUMBER(2),
    REFUNDDATE TIMESTAMP
);

COMMIT;